name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: pip install -r requirements.txt  # Replace with actual requirements file if needed
      
    - name: Run test
      run: |
        python -m unittest tests/test_cv.py
        # Store the exit code in a variable
        exit_code=$?
        # Print the exit code for debugging
        echo "Test exit code: $exit_code"
        # If the exit code is non-zero, the test failed
        if [ $exit_code -ne 0 ]; then
          exit 1
        fi